/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ServeFrontend': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, string>, never>
    'ServeAppJS': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, string>, never>
    'GenerateReport': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success?: boolean; report?: unknown }>, never>
    'GeneratePDF': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success?: boolean; pdf?: string; filename?: string }>, never>
    'GenerateDietRecommendation': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success?: boolean; dietRecommendation?: unknown }>, never>
    'DiseasePrediction': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success?: boolean; prediction?: unknown }>, never>
    'AnalyzeLabResults': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success?: boolean; analysis?: unknown }>, never>
    'AnalyzeImage': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success?: boolean; findings?: unknown; metadata?: unknown }>, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}